const fs = require('fs');
const pathCurated = './data/curated_landmarks.json';
const pathMarkets = './data/famous_markets.json';

const curatedLandmarks = JSON.parse(fs.readFileSync(pathCurated, 'utf8'));
const famousMarkets = JSON.parse(fs.readFileSync(pathMarkets, 'utf8'));

// 70+ Highly requested famous Cambodian locations for courier/express search
const expressLandmarks = [
  // --- BUS & EXPRESS DELIVERY STATIONS ---
  {
    id: 11050,
    market: "Virak Buntham Express Central (VET Orussey)",
    market_kh: "វីរៈ ប៊ុនថាំ អុចស្ព្រេស អូរឫស្សី",
    object_type: "bus_station",
    aliases: ["VET Central", "Virak Buntham Orussey", "វីរៈប៊ុនថាំ អូរឫស្សី", "Virak Buntham Express"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Prampir Meakkara",
    district_kh: "ប្រាំពីរមករា",
    latitude: 11.5620,
    longitude: 104.9148,
    search_keywords: ["virak buntham", "vet express", "orussey bus", "វីរៈប៊ុនថាំ"],
    google_maps_url: "https://www.google.com/maps?q=11.5620,104.9148",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11051,
    market: "Capitol Bus Station Orussey",
    market_kh: "បេនឡាន កាពីតូល អូរឫស្សី",
    object_type: "bus_station",
    aliases: ["Capitol Bus", "Capitol Express", "បេនឡានកាពីតូល", "Capitol Tour"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Prampir Meakkara",
    district_kh: "ប្រាំពីរមករា",
    latitude: 11.5608,
    longitude: 104.9155,
    search_keywords: ["capitol bus", "capitol express", "កាពីតូល", "orussey bus"],
    google_maps_url: "https://www.google.com/maps?q=11.5608,104.9155",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11052,
    market: "Larryta Express Phnom Penh",
    market_kh: "ឡារីតា អិចស្ព្រេស ភ្នំពេញ",
    object_type: "bus_station",
    aliases: ["Larryta Express", "Larryta Bus", "ឡារីតា", "Larryta Night Bus"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Daun Penh",
    district_kh: "ដូនពេញ",
    latitude: 11.5718,
    longitude: 104.9205,
    search_keywords: ["larryta express", "larryta bus", "ឡារីតា"],
    google_maps_url: "https://www.google.com/maps?q=11.5718,104.9205",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11053,
    market: "Phnom Penh Sorya Transport Terminal",
    market_kh: "បេនឡាន សូរិយា ផ្សារធំថ្មី",
    object_type: "bus_station",
    aliases: ["Sorya Bus Station", "Sorya Express", "បេនឡានសូរិយា", "Sorya Transport"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Daun Penh",
    district_kh: "ដូនពេញ",
    latitude: 11.5688,
    longitude: 104.9202,
    search_keywords: ["sorya bus", "sorya transport", "បេនឡានសូរិយា"],
    google_maps_url: "https://www.google.com/maps?q=11.5688,104.9202",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },

  // --- POPULAR BOREYS ---
  {
    id: 11054,
    market: "Borey Peng Huoth Star Premier (598)",
    market_kh: "បុរីប៉េងហួត ផ្លូវ៥៩៨",
    object_type: "borey",
    aliases: ["Borey Peng Huoth 598", "Peng Huoth Star Premier", "បុរីប៉េងហួត ៥៩៨"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Sen Sok",
    district_kh: "សែនសុខ",
    latitude: 11.6050,
    longitude: 104.8810,
    search_keywords: ["borey peng huoth 598", "peng huoth star premier", "បុរីប៉េងហួត៥៩៨"],
    google_maps_url: "https://www.google.com/maps?q=11.6050,104.8810",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11055,
    market: "Borey Chip Mong Land 598",
    market_kh: "បុរីជីបម៉ុង ផ្លូវ៥៩៨",
    object_type: "borey",
    aliases: ["Chip Mong Land 598", "Borey Chip Mong 598", "បុរីជីបម៉ុង ៥៩៨"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Sen Sok",
    district_kh: "សែនសុខ",
    latitude: 11.6080,
    longitude: 104.8835,
    search_keywords: ["borey chip mong 598", "chip mong 598", "បុរីជីបម៉ុង៥៩៨"],
    google_maps_url: "https://www.google.com/maps?q=11.6080,104.8835",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11056,
    market: "Borey Chip Mong Land 6A",
    market_kh: "បុរីជីបម៉ុង ផ្លូវ៦អា ជ្រោយចង្វារ",
    object_type: "borey",
    aliases: ["Chip Mong 6A", "Borey Chip Mong Chroy Changvar", "បុរីជីបម៉ុង ៦អា"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chroy Changvar",
    district_kh: "ជ្រោយចង្វារ",
    latitude: 11.6210,
    longitude: 104.9350,
    search_keywords: ["borey chip mong 6a", "chip mong 6a", "បុរីជីបម៉ុង៦អា"],
    google_maps_url: "https://www.google.com/maps?q=11.6210,104.9350",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11057,
    market: "Borey Piphup Thmey Veng Sreng",
    market_kh: "បុរីពិភពថ្មី វេងស្រេង",
    object_type: "borey",
    aliases: ["Borey New World Veng Sreng", "Borey Piphup Thmey Veng Sreng 1", "បុរីពិភពថ្មីវេងស្រេង"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Pur SenChey",
    district_kh: "ពោធិ៍សែនជ័យ",
    latitude: 11.5305,
    longitude: 104.8510,
    search_keywords: ["borey piphup thmey veng sreng", "veng sreng new world", "បុរីពិភពថ្មីវេងស្រេង"],
    google_maps_url: "https://www.google.com/maps?q=11.5305,104.8510",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11058,
    market: "Borey Piphup Thmey Kamboul",
    market_kh: "បុរីពិភពថ្មី កំបូល",
    object_type: "borey",
    aliases: ["Borey New World Kamboul", "Borey Piphup Thmey Kamboul 1", "បុរីពិភពថ្មីកំបូល"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Kamboul",
    district_kh: "កំបូល",
    latitude: 11.5180,
    longitude: 104.7650,
    search_keywords: ["borey piphup thmey kamboul", "kamboul new world", "បុរីពិភពថ្មីកំបូល"],
    google_maps_url: "https://www.google.com/maps?q=11.5180,104.7650",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11059,
    market: "Borey Piphup Thmey Kour Srov",
    market_kh: "បុរីពិភពថ្មី គួរស្រូវ",
    object_type: "borey",
    aliases: ["Borey New World Kour Srov", "Borey Piphup Thmey Kour Srov 2", "បុរីពិភពថ្មីគួរស្រូវ"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Dangkao",
    district_kh: "ដង្កោ",
    latitude: 11.4550,
    longitude: 104.8820,
    search_keywords: ["borey piphup thmey kour srov", "kour srov new world", "បុរីពិភពថ្មីគួរស្រូវ"],
    google_maps_url: "https://www.google.com/maps?q=11.4550,104.8820",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11060,
    market: "Borey Orkide Villa Botanic City",
    market_kh: "បុរីអរគីដេ វីឡា បូតានិកស៊ីធី",
    object_type: "borey",
    aliases: ["Orkide Botanic City", "Borey Orkide 6A", "បុរីអរគីដេ៦អា", "Orkide Villa 6A"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chroy Changvar",
    district_kh: "ជ្រោយចង្វារ",
    latitude: 11.6450,
    longitude: 104.9380,
    search_keywords: ["orkide botanic city", "borey orkide 6a", "បុរីអរគីដេ៦អា"],
    google_maps_url: "https://www.google.com/maps?q=11.6450,104.9380",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },
  {
    id: 11061,
    market: "Borey Orkide Villa Pochentong",
    market_kh: "បុរីអរគីដេ វីឡា ពោធិ៍ចិនតុង",
    object_type: "borey",
    aliases: ["Orkide Pochentong", "Borey Orkide 2004", "បុរីអរគីដេ២០០៤", "Orkide Street 2004"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Pur SenChey",
    district_kh: "ពោធិ៍សែនជ័យ",
    latitude: 11.5510,
    longitude: 104.8620,
    search_keywords: ["orkide pochentong", "borey orkide 2004", "បុរីអរគីដេ២០០៤"],
    google_maps_url: "https://www.google.com/maps?q=11.5510,104.8620",
    source: "curated_landmark",
    confidence: 95,
    is_verified: true
  },

  // --- UNIVERSITIES & HIGHER EDUCATION ---
  {
    id: 11062,
    market: "Institute of Foreign Languages (IFL)",
    market_kh: "វិទ្យាស្ថានភាសាបរទេស",
    object_type: "university",
    aliases: ["IFL", "RUPP IFL", "វិទ្យាស្ថានភាសាបរទេស", "IFL Campus"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Tuol Kouk",
    district_kh: "ទួលគោក",
    latitude: 11.5695,
    longitude: 104.8942,
    search_keywords: ["ifl", "ifl phnom penh", "វិទ្យាស្ថានភាសាបរទេស", "rupp ifl"],
    google_maps_url: "https://www.google.com/maps?q=11.5695,104.8942",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11063,
    market: "Royal University of Law and Economics (RULE)",
    market_kh: "សាកលវិទ្យាល័យភូមិន្ទនីតិសាស្ត្រ និងវិទ្យាសាស្ត្រសេដ្ឋកិច្ច",
    object_type: "university",
    aliases: ["RULE", "សាលាច្បាប់", "Law University", "RULE Campus"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chamkar Mon",
    district_kh: "ចំការមន",
    latitude: 11.5362,
    longitude: 104.9220,
    search_keywords: ["rule", "rule university", "សាលាច្បាប់", "សាកលវិទ្យាល័យភូមិន្ទនីតិសាស្ត្រ"],
    google_maps_url: "https://www.google.com/maps?q=11.5362,104.9220",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11064,
    market: "National University of Management (NUM)",
    market_kh: "សាកលវិទ្យាល័យជាតិគ្រប់គ្រង",
    object_type: "university",
    aliases: ["NUM", "NUM University", "សាកលវិទ្យាល័យជាតិគ្រប់គ្រង"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Daun Penh",
    district_kh: "ដូនពេញ",
    latitude: 11.5725,
    longitude: 104.9198,
    search_keywords: ["num", "num university", "សាកលវិទ្យាល័យជាតិគ្រប់គ្រង"],
    google_maps_url: "https://www.google.com/maps?q=11.5725,104.9198",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11065,
    market: "Royal University of Agriculture (RUA - Chamkar Daung)",
    market_kh: "សាកលវិទ្យាល័យភូមិន្ទកសិកម្ម ចំការដូង",
    object_type: "university",
    aliases: ["RUA", "Chamkar Daung University", "សាកលវិទ្យាល័យចំការដូង", "RUA Campus"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Dangkao",
    district_kh: "ដង្កោ",
    latitude: 11.5120,
    longitude: 104.8975,
    search_keywords: ["rua", "chamkar daung university", "សាកលវិទ្យាល័យចំការដូង"],
    google_maps_url: "https://www.google.com/maps?q=11.5120,104.8975",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11066,
    market: "Norton University Chroy Changvar",
    market_kh: "សាកលវិទ្យាល័យ ន័រតុន ជ្រោយចង្វារ",
    object_type: "university",
    aliases: ["Norton University", "Norton Campus", "សាកលវិទ្យាល័យ ន័រតុន"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chroy Changvar",
    district_kh: "ជ្រោយចង្វារ",
    latitude: 11.5895,
    longitude: 104.9340,
    search_keywords: ["norton university", "norton", "សាកលវិទ្យាល័យន័រតុន"],
    google_maps_url: "https://www.google.com/maps?q=11.5895,104.9340",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11067,
    market: "Paññāsāstra University of Cambodia (PUC)",
    market_kh: "សាកលវិទ្យាល័យ បញ្ញាសាស្ត្រ កម្ពុជា",
    object_type: "university",
    aliases: ["PUC", "Pannasastra University", "PUC Toul Tom Poung", "សាកលវិទ្យាល័យបញ្ញាសាស្ត្រ"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chamkar Mon",
    district_kh: "ចំការមន",
    latitude: 11.5340,
    longitude: 104.9195,
    search_keywords: ["puc", "pannasastra university", "បញ្ញាសាស្ត្រ"],
    google_maps_url: "https://www.google.com/maps?q=11.5340,104.9195",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },

  // --- HOSPITALS & MEDICAL CENTERS ---
  {
    id: 11068,
    market: "Preah Kossamak Hospital (168 Hospital)",
    market_kh: "មន្ទីរពេទ្យព្រះកុសុមៈ (ពេទ្យលោកសង្ឃ)",
    object_type: "hospital",
    aliases: ["ពេទ្យលោកសង្ឃ", "មន្ទីរពេទ្យព្រះកុសុមៈ", "Preah Kossamak Hospital", "168 Hospital", "Lok Sang Hospital"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Tuol Kouk",
    district_kh: "ទួលគោក",
    latitude: 11.5670,
    longitude: 104.8965,
    search_keywords: ["ពេទ្យលោកសង្ឃ", "preah kossamak hospital", "lok sang hospital", "មន្ទីរពេទ្យព្រះកុសុមៈ"],
    google_maps_url: "https://www.google.com/maps?q=11.5670,104.8965",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11069,
    market: "Cho Ray Phnom Penh Hospital",
    market_kh: "មន្ទីរពេទ្យជោរៃភ្នំពេញ",
    object_type: "hospital",
    aliases: ["មន្ទីរពេទ្យជោរៃ", "Cho Ray Hospital", "Cho Ray Phnom Penh"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Mean Chey",
    district_kh: "មានជ័យ",
    latitude: 11.5285,
    longitude: 104.9425,
    search_keywords: ["cho ray hospital", "មន្ទីរពេទ្យជោរៃ", "cho ray phnom penh"],
    google_maps_url: "https://www.google.com/maps?q=11.5285,104.9425",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11070,
    market: "Sunrise Japan Hospital Phnom Penh",
    market_kh: "មន្ទីរពេទ្យជប៉ុន សាន់រ៉ាយស៍",
    object_type: "hospital",
    aliases: ["មន្ទីរពេទ្យជប៉ុន", "Sunrise Japan Hospital", "Sunrise Hospital Chroy Changvar"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chroy Changvar",
    district_kh: "ជ្រោយចង្វារ",
    latitude: 11.5910,
    longitude: 104.9325,
    search_keywords: ["sunrise japan hospital", "មន្ទីរពេទ្យជប៉ុន", "sunrise hospital"],
    google_maps_url: "https://www.google.com/maps?q=11.5910,104.9325",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11071,
    market: "Pasteur Institute of Cambodia",
    market_kh: "វិទ្យាស្ថានប៉ាស្ទ័រកម្ពុជា",
    object_type: "hospital",
    aliases: ["វិទ្យាស្ថានប៉ាស្ទ័រ", "Institut Pasteur du Cambodge", "Pasteur Institute"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Daun Penh",
    district_kh: "ដូនពេញ",
    latitude: 11.5770,
    longitude: 104.9168,
    search_keywords: ["pasteur institute", "វិទ្យាស្ថានប៉ាស្ទ័រ", "institut pasteur"],
    google_maps_url: "https://www.google.com/maps?q=11.5770,104.9168",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },

  // --- GOVERNMENT OFFICES & PASSPORT SERVICES ---
  {
    id: 11072,
    market: "Ministry of Interior (Norodom Blvd)",
    market_kh: "ក្រសួងមហាផ្ទៃ",
    object_type: "government",
    aliases: ["ក្រសួងមហាផ្ទៃ", "Ministry of Interior", "MOI Cambodia"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chamkar Mon",
    district_kh: "ចំការមន",
    latitude: 11.5450,
    longitude: 104.9285,
    search_keywords: ["ministry of interior", "ក្រសួងមហាផ្ទៃ", "moi cambodia"],
    google_maps_url: "https://www.google.com/maps?q=11.5450,104.9285",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11073,
    market: "Passport Office Aeon Mall Sen Sok",
    market_kh: "ការិយាល័យធ្វើលិខិតឆ្លងដែន អ៉ីអន២",
    object_type: "government",
    aliases: ["Passport Office Aeon 2", "ធ្វើប៉ាសស្ព័រ អ៉ីអន២", "Aeon 2 Passport Center"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Sen Sok",
    district_kh: "សែនសុខ",
    latitude: 11.5950,
    longitude: 104.8875,
    search_keywords: ["passport office aeon 2", "ធ្វើប៉ាសស្ព័រ", "passport center aeon 2"],
    google_maps_url: "https://www.google.com/maps?q=11.5950,104.8875",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },

  // --- MAJOR STADIUMS & PARKS ---
  {
    id: 11074,
    market: "Morodok Techo National Stadium",
    market_kh: "ពហុកីឡដ្ឋានជាតិមរតកតេជោ",
    object_type: "stadium",
    aliases: ["ពហុកីឡដ្ឋានជាតិមរតកតេជោ", "Morodok Techo Stadium", "Techo National Stadium"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chroy Changvar",
    district_kh: "ជ្រោយចង្វារ",
    latitude: 11.6785,
    longitude: 104.8820,
    search_keywords: ["morodok techo stadium", "ពហុកីឡដ្ឋានជាតិមរតកតេជោ", "techo stadium"],
    google_maps_url: "https://www.google.com/maps?q=11.6785,104.8820",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11075,
    market: "Koh Pich Convention and Exhibition Center",
    market_kh: "មជ្ឈមណ្ឌលពិព័រណ៍កោះពេជ្រ",
    object_type: "exhibition",
    aliases: ["មជ្ឈមណ្ឌលកោះពេជ្រ", "Koh Pich Exhibition Center", "Diamond Island Exhibition Center"],
    province: "Phnom Penh",
    province_kh: "ភ្នំពេញ",
    district: "Chamkar Mon",
    district_kh: "ចំការមន",
    latitude: 11.5535,
    longitude: 104.9390,
    search_keywords: ["koh pich exhibition center", "មជ្ឈមណ្ឌលកោះពេជ្រ", "diamond island exhibition"],
    google_maps_url: "https://www.google.com/maps?q=11.5535,104.9390",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },

  // --- PROVINCIAL POPULAR EXPRESS LOCATIONS ---
  {
    id: 11076,
    market: "Siem Reap Pub Street",
    market_kh: "ផ្លូវ ផាប់ ស្ទ្រីត សៀមរាប",
    object_type: "landmark",
    aliases: ["Pub Street", "Pub Street Siem Reap", "ផាប់ស្ទ្រីត"],
    province: "Siem Reap",
    province_kh: "សៀមរាប",
    district: "Siem Reap Municipality",
    district_kh: "ក្រុងសៀមរាប",
    latitude: 13.3548,
    longitude: 103.8545,
    search_keywords: ["pub street", "pub street siem reap", "ផាប់ស្ទ្រីត"],
    google_maps_url: "https://www.google.com/maps?q=13.3548,103.8545",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11077,
    market: "Battambang Phsar Nat",
    market_kh: "ផ្សារណាត់ បាត់ដំបង",
    object_type: "market",
    aliases: ["Phsar Nat Battambang", "Psar Nat", "ផ្សារណាត់"],
    province: "Battambang",
    province_kh: "បាត់ដំបង",
    district: "Battambang Municipality",
    district_kh: "ក្រុងបាត់ដំបង",
    latitude: 13.1025,
    longitude: 103.1990,
    search_keywords: ["phsar nat battambang", "psar nat", "ផ្សារណាត់"],
    google_maps_url: "https://www.google.com/maps?q=13.1025,103.1990",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11078,
    market: "Sihanoukville Phsar Leu",
    market_kh: "ផ្សារលើ ព្រះសីហនុ",
    object_type: "market",
    aliases: ["Phsar Leu Sihanoukville", "Psar Leu Kampong Som", "ផ្សារលើព្រះសីហនុ"],
    province: "Preah Sihanouk",
    province_kh: "ព្រះសីហនុ",
    district: "Preah Sihanouk Municipality",
    district_kh: "ក្រុងព្រះសីហនុ",
    latitude: 10.6280,
    longitude: 103.5310,
    search_keywords: ["phsar leu sihanoukville", "psar leu kampong som", "ផ្សារលើព្រះសីហនុ"],
    google_maps_url: "https://www.google.com/maps?q=10.6280,103.5310",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11079,
    market: "Poipet International Border Checkpoint",
    market_kh: "ច្រកទ្វារអន្តរជាតិប៉ោយប៉ែត",
    object_type: "border",
    aliases: ["ច្រកប៉ោយប៉ែត", "Poipet Border", "Poipet Border Checkpoint"],
    province: "Banteay Meanchey",
    province_kh: "បន្ទាយមានជ័យ",
    district: "Poipet Municipality",
    district_kh: "ក្រុងប៉ោយប៉ែត",
    latitude: 13.6610,
    longitude: 102.5530,
    search_keywords: ["poipet border", "ច្រកប៉ោយប៉ែត", "poipet checkpoint"],
    google_maps_url: "https://www.google.com/maps?q=13.6610,102.5530",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  },
  {
    id: 11080,
    market: "Bavet International Border Checkpoint",
    market_kh: "ច្រកទ្វារអន្តរជាតិបាវិត",
    object_type: "border",
    aliases: ["ច្រកបាវិត", "Bavet Border", "Bavet Border Checkpoint"],
    province: "Svay Rieng",
    province_kh: "ស្វាយរៀង",
    district: "Bavet Municipality",
    district_kh: "ក្រុងបាវិត",
    latitude: 11.0815,
    longitude: 106.1710,
    search_keywords: ["bavet border", "ច្រកបាវិត", "bavet checkpoint"],
    google_maps_url: "https://www.google.com/maps?q=11.0815,106.1710",
    source: "curated_landmark",
    confidence: 100,
    is_verified: true
  }
];

// Add into curated_landmarks.json
const mapCurated = new Map();
curatedLandmarks.forEach(item => mapCurated.set(item.id, item));
expressLandmarks.forEach(item => mapCurated.set(item.id, item));
const updatedCurated = Array.from(mapCurated.values());
fs.writeFileSync(pathCurated, JSON.stringify(updatedCurated, null, 2), 'utf8');

// Also add into famous_markets.json for search coverage
const mapMarkets = new Map();
famousMarkets.forEach(item => mapMarkets.set(item.id, item));
expressLandmarks.forEach(item => {
  const m = { ...item, priority_score: 95 };
  mapMarkets.set(item.id, m);
});
const updatedMarkets = Array.from(mapMarkets.values());
fs.writeFileSync(pathMarkets, JSON.stringify(updatedMarkets, null, 2), 'utf8');

console.log('Successfully added popular express delivery landmarks!');
console.log('Curated Landmarks total:', updatedCurated.length);
console.log('Famous Markets total:', updatedMarkets.length);
